rm -r ./css
rm -r ./js
rm -r ./page
rm -r ./posts
rm -r ./tags
rm -r ./404.html
rm -r android-chrome-192x192.png
rm -r android-chrome-512x512.png
rm -r apple-touch-icon.png
rm -r browserconfig.xml
rm -r favicon-16x16.png
rm -r favicon-32x32.png
rm -r favicon.ico
rm -r index.html
rm -r index.xml
rm -r mstile-150x150.png
rm -r robots.txt
rm -r site.webmanifest
rm -r sitemap.xml